services:
  frontend:
    build: .
    ports:
      - "8050:8050"
    # env_file:
    #   - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_BASE_URL=${API_BASE_URL}
      - DEBUG=${DEBUG}
    restart: unless-stopped
