services:
  frontend:
    build: .
    ports:
      - "8050:8050"
    # env_file:
    #   - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_BASE_URL=${API_BASE_URL}
      - API_PUBLIC_URL=${API_PUBLIC_URL}
      - DEBUG=${DEBUG}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    restart: unless-stopped
    networks:
      - default
      - proxy-network

# Das hier steht ganz am Ende der Datei:
networks:
  proxy-network:
    name: proxy-network  # WICHTIG: Hier muss der exakte Name des Nginx-Netzwerks stehen (z.B. npm_default)
    external: true